### ISSUE TITLE
Alternative evaluation of localStorage.getItem()

### ISSUE THREAD

**Issue by d1che** [pepijngieles/knister#8]
https://github.com/pepijngieles/knister/blob/f62190e3dc80b2f867397c78a406dea4552b7323/js/script.js#L88

localStorage.getItem() will return `undefined` instead of `null`. It might be better to check for falseness instead of falsyness.

**Comment by pepijngieles** [comment]
Thanks for thinking along @d1che. I've been looking into this and found [this answer on StackOverflow](https://stackoverflow.com/a/16010881/2215004) that refers to the official documentation, stating `null` should be returned in case the key doesn't exist. So I guess I'll hold onto the current approach.
